CREATE TABLE bodytype (
    id   integer generated by default as identity constraint bodytype_pkey primary key,
    name varchar(255)
);

CREATE TABLE brand (
    id integer generated by default as identity
    constraint brand_pkey
    primary key,
    name varchar (255)
);

CREATE TABLE users (
    id integer generated by default as identity constraint users_pkey primary key,
    email    varchar(255),
    name     varchar(255),
    password varchar(255)
);

CREATE TABLE car
(
    id integer generated by default as identity constraint car_pkey primary key,
    description  varchar(255),
    issaled      boolean,
    body_type_id integer constraint fk_body_type_id references bodytype,
    brand_id integer constraint fk_brand_id references brand,
    user_id integer constraint fk_user_id references users
);